groups:
  - bash
  - zsh
	- developer
recipes:
  mac_os_x:
    - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
    - osxdefaults::menu_add_battery_percentage
    - osxdefaults::set_computer_name
attributes:
	dotfiles:
		vimusers:
			- root
			- ac-nalmeida
		vim:
			bundle:
				- gitgutter: git://github.com/airblade/vim-gitgutter.git
        - airline: https://github.com/bling/vim-airline
        - syntastic: git://github.com/scrooloose/syntastic.git
        - nerdtree: https://github.com/scrooloose/nerdtree.git
        - vim-css-color: https://github.com/ap/vim-css-color
	git:h
		name: Norton Almeida
    email: norton.alemida@bloomingdales.com
  osxdefaults:
    computername: AC-NALMEIDA-PC
  homebrewalt:
    apps:
      - git-extras
      - google-drive
      - kaleidoscope
      - bartender
      - hazel
      - sonos
      - keepingyouawake
      - tower
      - vlc
      - slack
      - mailplane
    cask_apps:
      - sourcetree
      - caffeine